Repository ashokdey/private-io, pull requests merged in 2019-10, with the labels that each got.

#11 UPDATED NPM PACKAGES
  package-lock.json
  package.json
Labels: Hacktoberfest, beginner friendly, enhancement, under review

#12 Added ESLint + Airbnb rules
  .eslintrc.js
  package-lock.json
  package.json
Labels: Hacktoberfest, beginner friendly, review complete

#14 Updated babel to latest version and switched to recommend preset-env.
  .babelrc
  package-lock.json
  package.json
  public/js/bundle.js
Labels: Hacktoberfest, enhancement, under review

#13 fixed network error issue
  client/app.jsx
  public/index.html
Labels: bug-fix

#17 Enhancements and fixes
  .babelrc
  .eslintrc.js
  .vscode/settings.json
  README.md
  client/app.jsx
  client/components/Cover.jsx
  package-lock.json
  package.json
  public/index.html
  public/js/bundle.js
Labels: bug-fix, enhancement

#21 :tada: Fixed placeholder bug
  .gitignore
  client/components/Cover.jsx
  package-lock.json
  public/js/bundle.js
Labels: Hacktoberfest, bug-fix, enhancement
